### ISSUE TITLE
Implement new wake up cmd.

### ISSUE THREAD

**Issue by darkman7hr** [paulvha/sds011#1]
Hi,
I know this is outdated git but it still works fine. Just wake from sleep does not work.
While googling, found this::

`Solution:

In the current datasheet, it is specified that the proper wake-up procedure is to send a 19-byte sequence very similar to the SLEEP command. If you modify "sds011.cpp" by adding the struct below and changing the wakeup function similar to what I tried below then everything seems to work just fine!

Here's a link to the spec, refer to pages 7 and 8: [https://nettigo.pl/attachments/415]

static const byte WAKECMD[19] = {
	0xAA,	// head
	0xB4,	// command id
	0x06,	// data byte 1
	0x01,	// data byte 2 (set mode)
	0x01,	// data byte 3 (wake up)
	0x00,	// data byte 4
	0x00,	// data byte 5
	0x00,	// data byte 6
	0x00,	// data byte 7
	0x00,	// data byte 8
	0x00,	// data byte 9
	0x00,	// data byte 10
	0x00,	// data byte 11
	0x00,	// data byte 12
	0x00,	// data byte 13
	0xFF,	// data byte 14 (device id byte 1)
	0xFF,	// data byte 15 (device id byte 2)
	0x06,	// checksum
	0xAB	// tail
};
// --------------------------------------------------------
// SDS011:wakeup
// --------------------------------------------------------
void SDS011::wakeup() {
	for (uint8_t i = 0; i < 19; i++) {
		sds_data->write(WAKECMD[i]);
	}
	sds_data->flush();
	while (sds_data->available() > 0) {
		sds_data->read();
	}
}`

**Comment by paulvha** [comment]
Thanks. Indeed LONG ago :-)

I think the code is sending the correct structure by calling: 
Set_Sleep_Work_Mode(MODE_WORK), it sets data Byte 2 as 1
Set_Sleep_Work_Mode(MODE_SLEEP), it sets data byte 2 is set as 0

What it does not do is wait for data->available check. Is that what I should add ?

**Comment by darkman7hr** [comment]
I don't know. I'm lausy coder :) When it goes to sleep it can never go back to work mode. So I googled and found this. I guess in some models (guess it's firmware thing) it doesn't wake up. It's unresponsive.

**Comment by paulvha** [comment]
Thanks for bringing this to my attention. I will try when I find time. Since then I have moved on to the SPS30 from Sensirion. It is a better sensor with longer lifetime.

**Comment by darkman7hr** [comment]
I've googled it but I cant see does it have like pipe intake? I intend to use it outdoor. (SPS30)

**Comment by paulvha** [comment]
No it does not .. but I know these guys are using it for outdoor usage. https://www.ohnics.online/over/. Maybe send them a mail and ask for their opinion.

**Comment by paulvha** [comment]
Today I found time to test wakeup. While the right wakup sequence was sent it would not respond to me either. After long debugging I found that the root cause was related to a sequence error:  after setting to sleep, the command start reading was still sent (but never answered as the SDS011 was in sleep). The firmware did not like that. I changed the sequence and now it works. 
Previously I had already changed from C-structure to C++ structure, but apparently never sent to GitHub. Hence you have now a new version (with some different command line options).

**Comment by darkman7hr** [comment]
Unfortunately for me, it still doesn't work.
Plus it loops on every command i've tried.

```root@ttn-gateway:~# sds -m
Connecting to SDS-011
Connected
Currently in Working mode
Continuously capturing data
PM 2.5 1.800000, PM10 5.300000
PM 2.5 1.800000, PM10 5.200000
PM 2.5 1.800000, PM10 5.300000
PM 2.5 1.800000, PM10 5.200000
PM 2.5 1.700000, PM10 4.900000
PM 2.5 1.700000, PM10 5.500000
PM 2.5 1.700000, PM10 5.500000
PM 2.5 1.700000, PM10 5.100000
PM 2.5 1.700000, PM10 4.900000
PM 2.5 1.600000, PM10 4.700000
Number of requested loops reached
root@ttn-gateway:~# sds -f
Connecting to SDS-011
Connected
Firmware date (Y-M-D): 18-11-16
Continuously capturing data
PM 2.5 2.200000, PM10 6.800000
PM 2.5 2.300000, PM10 6.800000
PM 2.5 2.300000, PM10 7.000000
PM 2.5 2.300000, PM10 7.000000
PM 2.5 2.200000, PM10 6.600000
PM 2.5 2.200000, PM10 7.000000
PM 2.5 2.200000, PM10 7.100000
PM 2.5 2.100000, PM10 7.000000
PM 2.5 2.100000, PM10 7.300000
PM 2.5 2.100000, PM10 7.500000
Number of requested loops reached
root@ttn-gateway:~# sds -M S
Connecting to SDS-011
Connected
Set to sleep
root@ttn-gateway:~# sds -M W
Connecting to SDS-011
Error during trying to connect
root@ttn-gateway:~#

**Comment by paulvha** [comment]
About the loops : that is correct you can set this now on the command line with -l option. setting as -l 0 will loop forever.

To wakeup, must be a sds-011 firmware issue. Just tested on mine the same command and it works with 2018 firmware.

./sds
Connecting to SDS-011
Connected
Continuously capturing data
PM 2.5 1.700000, PM10 3.500000
PM 2.5 1.700000, PM10 3.700000
PM 2.5 1.700000, PM10 3.700000
PM 2.5 1.800000, PM10 3.800000
PM 2.5 1.800000, PM10 3.800000
PM 2.5 1.800000, PM10 4.600000
PM 2.5 1.700000, PM10 4.300000
PM 2.5 1.700000, PM10 4.300000
PM 2.5 1.700000, PM10 4.300000
PM 2.5 1.800000, PM10 4.500000
Number of requested loops reached
./sds -f
Connecting to SDS-011
Connected
Firmware date (Y-M-D): 18-1-18
Continuously capturing data
PM 2.5 2.000000, PM10 5.000000
PM 2.5 2.100000, PM10 5.200000
PM 2.5 2.100000, PM10 5.400000
PM 2.5 2.100000, PM10 5.500000
PM 2.5 2.100000, PM10 5.400000
PM 2.5 2.000000, PM10 5.300000
PM 2.5 2.000000, PM10 5.200000
PM 2.5 2.000000, PM10 5.200000
PM 2.5 2.000000, PM10 5.000000
PM 2.5 2.000000, PM10 5.200000
Number of requested loops reached
./sds -M S
Connecting to SDS-011
Connected
Set to sleep
./sds -M W
Connecting to SDS-011
Connected
wait 30 seconds to stabalize working mode
Continuously capturing data
PM 2.5 1.900000, PM10 3.500000
PM 2.5 2.000000, PM10 3.900000
PM 2.5 2.000000, PM10 4.000000
PM 2.5 2.000000, PM10 4.200000
PM 2.5 2.000000, PM10 4.100000
PM 2.5 1.900000, PM10 4.100000
PM 2.5 2.000000, PM10 4.600000
PM 2.5 2.000000, PM10 4.800000
PM 2.5 1.900000, PM10 4.800000
PM 2.5 2.000000, PM10 4.800000
Number of requested loops reached

**Comment by darkman7hr** [comment]
I've tried to find or download firmware for the actual device but to no avail. I'm pretty sure there are differences in that area of sleep/resume. I guess I'll keep it on for a while. reboot of a pi helps.
